### ISSUE TITLE
签名方法错误导致签名校验不通过

### ISSUE THREAD

**Issue by Aixinwei** [gateio/gateapi-go#1]
client.go第270行：
msg := fmt.Sprintf("%s\n%s\n%s\n%s\n%s", method, url, url.RawPath, hashedPayload, t)
会导致签名校验不通过
应改为：
msg := fmt.Sprintf("%s\n%s\n%s\n%s\n%s", method, url.Path, url.RawQuery, hashedPayload, t)

**Comment by Aixinwei** [comment]
url.RawPath应替换为url.RawQuery

**Comment by revilwang** [comment]
感谢指正，4.6.0 之后的版本已经将该问题修复
