### ISSUE TITLE
如何像APP中那样显示当前账户的总资产?

### ISSUE THREAD

**Issue by Turing-Chu** [gateio/gateapi-go#10]
如何像APP中那样获取当前账户的总资产?
比如指定以某种币种计算(BTC/ETH/USDT/CNY等)，返回当前账户以该币种计算的总资产

**Comment by revilwang** [comment]
目前 API 不提供类似数据，但是可以考虑分成两步操作：

1. 将余额里所有的币种按各市场里 ticker 里的 last 最新价折算成 USDT，然后累加即可得到 USDT 的总额
2. 如果是要转换成 BTC,ETH 等加密货币，则同样获取对应市场的 last 最新价进行折算，得到 BTC 或者 ETH 的总额
3. 如果是 CNY 之类的法币，则建议通过外部途径获取 USDT 折算成法币的汇率，进而得到法币的总额

**Comment by Turing-Chu** [comment]
当前就是这样做的。之所以问这个问题就是想优化，目前是用的接口，没有用socket。所以用接口拉取一堆币种的现价信息就觉得性能不咋地。

**Comment by revilwang** [comment]
可以考虑内部维护一个各市场价格的缓存，异步更新这个价格。

不过依然推荐使用 WebSocket 方式，WebSocket 推送数据会更加及时，HTTP 的数据会存在一定延时。现货 WebSocket V4 最近也刚上线，可以考虑对接做个辅助

**Comment by Turing-Chu** [comment]
ok, tks.
