### ISSUE TITLE
client.MarginApi.ListLoans无法查询抵押借币订单

### ISSUE THREAD

**Issue by young66** [gateio/gateapi-go#12]
使用v4的api /margin/loans    client.MarginApi.ListLoans查询借入借出订单
如果传side=lend, status=finished可以正常查询借出订单；
如果传side=borrow，status=open/loaned/finished都返回空,实际有若干个抵押借币订单。

**Comment by revilwang** [comment]
抵押借币订单不在这个接口的覆盖范围，抵押借币目前接口并未开放

**Comment by young66** [comment]
有版本规划吗？自动续借碰到高息还必须手工改单

**Comment by young66** [comment]
抵押借币的订单增删改查有rest、websocket的api接口吗

**Comment by young66** [comment]
在其他issue跟踪。
https://github.com/gateio/rest/issues/54
