### ISSUE TITLE
杠杆账户利息

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-go#14]
杠杆账户列表 (GET /margin/accounts). 接口怎么不返回借币对应未还的利息

**Comment by revilwang** [comment]
这个我们安排加一下

**Comment by HFLeon** [comment]
好的，更新完麻烦这里通知一下哈

**Comment by revilwang** [comment]
逐仓杠杆查询已新增 `interest` 返回，更新到最新的 v6.21.2 就可以使用
