### ISSUE TITLE
借入或借出

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-go#15]
借入或借出接口：POST /margin/loans
1、参数rate[贷款利率]在借入的情况下是必须要设置的吗？怎么计算？
2、参数amount[贷款额度]该怎么计算呢，借币数量*最新市价？
3、参数days[贷款天数]在借入的情况下是必须要设置的吗？怎么计算？

**Comment by revilwang** [comment]
1. rate 自行从市场里 `GET /margin/funding_book` 挂的借出选择自己适合的利率
2. amount 就是币的数量，不用做价格转换
3. days 目前只支持 10 ，设置为 10 即可

**Comment by HFLeon** [comment]
好的，谢谢
