### ISSUE TITLE
no matching versions for query "upgrade"

### ISSUE THREAD

**Issue by sami2020pro** [gateio/gateapi-go#16]
Hello :hand:
I ran the following command:
```
go get github.com/gateio/gateapi-go
```
And I got the following output :
```
go get github.com/gateio/gateapi-go: no matching versions for query "upgrade"
```
And I looked at the [go.mod](https://github.com/gateio/gateapi-go/blob/master/go.mod) file and it had the following contents:
```
...
go 1.12
...
```
Finally, I checked the current version, which you can see below:
```
go1.16.5
```

Please update this project :exclamation:

**Comment by revilwang** [comment]
Version in `go.mod` doesn't need to follow your own project's go version. You should use 

```
go get github.com/gateio/gateapi-go/v6
```

as shown in the getting started guide.
