### ISSUE TITLE
GetTotalBalanceOpts

### ISSUE THREAD

**Issue by chengkenlee** [gateio/gateapi-go#28]
I encountered a problem in the development process. Can you help me solve it,
As for the non essential parameter, how is it assigned,
For example:

"currency" parameter in "GetTotalBalance" module,
I set the "currency" parameter to, but I don't know how to set it,

The document indicates that GetTotalBalanceOpts struct can be used.

Can you provide an example?

**Comment by revilwang** [comment]
```go
opts := &gateapi.GetTotalBalanceOpts{Currency: optional.NewString(currency)}
```

**Comment by chengkenlee** [comment]
Thank you very much for helping me solve this problem!!
