### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by boner-kun** [gateio/gateapi-go#31]
Starting in Go 1.16, installing executables with go get is deprecated. go install may be used instead..
In official api website: https://github.com/gateio/gateapi-go , to get the package the command is:
go get github.com/gateio/gateapi-go/v6
and it does not work anymore and is needed to use go install , but I get error: is not a main package, after all week of researching I still cannot get to an answer, how to install the package.
![image](https://user-images.githubusercontent.com/103522767/163145871-941cf577-dbf9-4357-942f-23ff6f7bba07.png)

I reinstalled to older version of Go 1.15, where are no major changes, but using official SDK it is still does not work, I used version v5 of package and it did download but was not added to mod.
![image](https://user-images.githubusercontent.com/103522767/163146031-7790b1c6-c6e2-4b35-a16b-c832bfdaf67b.png)

Please help me solve the issue.

**Comment by revilwang** [comment]
We'll have a check

**Comment by revilwang** [comment]
`go get` is deprecated by `go install` **only when you're installing executables**. But `gateapi-go` is not an executable. You still need to use `go get` to add it as your own executable application's dependency.

**Comment by boner-kun** [comment]
Thank you for fast response, 
even though I am using go get, I still cannot add it: no matching versions for query "upgrade" / "latest"
![Screenshot from 2022-04-13 16-47-51](https://user-images.githubusercontent.com/103522767/163195354-84d6359c-0430-41e5-acb5-777bbba34142.png)

**Comment by boner-kun** [comment]
@0x5487 
Hello, I finally made it work: I created a folder in: $GOPATH/src , and it seems , that I could not create it in $GOROOT/src, it would bring that error "no matching errors":
![image](https://user-images.githubusercontent.com/103522767/163381046-9319eef9-3d9d-45ad-89b7-cc764805952d.png)

Unfortunately, Vscode cannot find a package, while trying to run a simple get_currency script:
![image](https://user-images.githubusercontent.com/103522767/163381350-7ae4b58d-a9e1-464e-bdaf-78bdf704d4d2.png)

However, VS seems to recognize: import github..../v6 and modules and are not labeled with red underline.:
![image](https://user-images.githubusercontent.com/103522767/163382931-f3a91ec6-4528-4eb6-b49d-165cae6db623.png)
 
Here is my `go env`
![image](https://user-images.githubusercontent.com/103522767/163381616-4dc1f3aa-ff94-4eca-86d3-fca5f80d602d.png)

**Comment by 0x5487** [comment]
@boner-kun,
I am afraid that you created your project under GOPATH ( `/home/captain/go`) which might not be a good choice.   I would suggest moving the project to `/home/captain/gateapi/` and trying that again :)

**Comment by boner-kun** [comment]
@0x5487 @revilwang 
I listened for both suggestions, changed project directory and name. However, it seems that some little thing just missing.
![image](https://user-images.githubusercontent.com/103522767/163449831-fc223d0c-26a2-46bd-ade6-29f22bd8b3ee.png)

I run go code from $HOME directory, maybe there is something I am missing I need to do? I am beginner in ubuntu and golang, so any little tip might change the course of this issue.
![image](https://user-images.githubusercontent.com/103522767/163450179-24b0d75b-9531-4e1c-809f-b7b00443e606.png)

**Comment by 0x5487** [comment]
@boner-kun,
It seems to me that you put your `main.go` under $Home directory.  I am afraid the file should be moved to `~/projectgate/main.go`.

**Comment by boner-kun** [comment]
@0x5487  @revilwang 
Thank you Kind Sirs, with your suggestions it finally works.
