### ISSUE TITLE
api写非常难看， 每个函数都有大量可以复用的代码段， 丢人

### ISSUE THREAD

**Issue by hstcscolor** [gateio/gateapi-go#32]

**Comment by revilwang** [comment]
不知道你有没有想过这个代码可能不是写出来的？

**Comment by hstcscolor** [comment]
> 

怎么产生的和我有什么关系， 既然没有可读性，搞个二进制文件吧。几个开源的项目都把gate的api抹掉了不是没原因的。

**Comment by revilwang** [comment]
我理解抱怨是解决不了问题的，我们通过代码生成工具这种自动化的方式最大化程度保证 SDK 和文档同步更新，有得也有舍，重复性代码在不影响运行效率的情况下也是能简化代码生成的逻辑，如果能提出一些更有操作性的改善方法能够调整我们的代码生成模板，我觉得对于双方来说都是个更好的解决方法

**Comment by hstcscolor** [comment]
说明你么的接口变化多端？是这意思吗？

**Comment by revilwang** [comment]
API 接口会新增功能，SDK 里绝大部分更新都只是对新增接口的参数设置做一些处理，所以我们采用了程序化的方式将这些参数设置直接进行自动化生成处理，因为核心的调用逻辑基本是长期保持不变的，这样也减少了很多人工维护的成本（人工自己写更容易出错），而且从实用性和性能上来说，这种程序化生成代码的方式对于运行时来说并不会有什么损耗

所以如果您能对于我们提交的核心处理逻辑有更好的优化建议，或者每个请求方法里的代码逻辑有什么更好的写法，欢迎提出新的建议

**Comment by hstcscolor** [comment]
自己已重写完
