### ISSUE TITLE
怎么用NGINX搭建websocket代理

### ISSUE THREAD

**Issue by Turing-Chu** [gateio/gateapi-go#5]
因gateio 服务器在国外，无法直接访问，现在需要将http接口请求改为websocket请求，请问怎么用nginx搭建websocket的代理？

**Comment by revilwang** [comment]
该问题超出本项目覆盖的范围，可以参阅 nginx 官方的文档：https://www.nginx.com/blog/websocket-nginx/

**Comment by Turing-Chu** [comment]
配好了。
