### ISSUE TITLE
SpotApi.CreateOrder 接口返回的信息（LedgerRecord）固定报错

### ISSUE THREAD

**Issue by zhangriyueming** [gateio/gateapi-go#6]
原因：api 接口返回的 id 是数字，但是本项目中 LedgerRecord 的 id 是 string 导致 json unmarshal 错误。

**Comment by revilwang** [comment]
`LedgerRecord` 是 WalletApi 里返回的，而且确认了这个 id 字段返回的的确是 string 类型。确认是这个 model 吗？

**Comment by zhangriyueming** [comment]
确认，调用 Widthdraw 接口的时候 API 返回的是 number 不是 string 类型。现在的生产环境中报错。

**Comment by revilwang** [comment]
还是需要你确认下具体是哪个接口，提现接口文档里说明的是不返回 body
