### ISSUE TITLE
请求经常超时

### ISSUE THREAD

**Issue by aveyuan** [gateio/gateapi-go#9]
目前做的账户轮询测试，超时的几率太大了,结果返回
`https://api.gateio.ws/api/v4/spot/accounts": net/http: TLS handshake timeout`

**Comment by revilwang** [comment]
从错误上来看，到服务端的网络不稳定

建议选择就近在 AWS 东京区域的机器上访问

**Comment by aveyuan** [comment]
> 从错误上来看，到服务端的网络不稳定
> 
> 建议选择就近在 AWS 东京区域的机器上访问
有地址列表吗？

**Comment by revilwang** [comment]
你可能没理解我的意思。API服务在AWS东京区域，如果你有一台AWS东京区域的ec2，在那里运行程序，就不会容易碰到网络问题

**Comment by Turing-Chu** [comment]
之前查了下ip地址，就把服务器买到东京了。

平时偶尔会遇到 `label: SERVER_ERROR, message: Internal server error`/ `417 Expectation Failed,  `其他都是业务错误了

**Comment by revilwang** [comment]
嗯，这类错误是服务处理出错，如升级或者系统过载时会出现，不属于网络连接问题

**Comment by aveyuan** [comment]
> 之前查了下ip地址，就把服务器买到东京了。
> 
> 平时偶尔会遇到 `label: SERVER_ERROR, message: Internal server error`/ `417 Expectation Failed, `其他都是业务错误了

3Q
